### ISSUE TITLE
EDISIO Température type ETS-100

### ISSUE THREAD

**Issue by Doubledom45** [racletteparty/HacsMyRfPlayer#12]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Décodage EDISIO Absente

### Describe the solution you'd like

Décodage de la trame suivant protocole Edisio

### Describe alternatives you've considered

Voir les informations de L'api
![image](https://github.com/user-attachments/assets/2aeef14a-5566-43b9-8fcb-cd9dbff0e2c9)
![image](https://github.com/user-attachments/assets/cc863927-fb93-40a6-9a41-da9a7b8b07d5)

### Additional context

 DEBUG (MainThread) [custom_components.myrfplayer.rfplayerlib.protocol] received packet: ZIA33{ "frame" :{"header": {"frameType": "0", "cluster": "0", "dataFlag": "1", "rfLevel": "-58", "floorNoise": "-98", "rfQuality": "10", "protocol": "16", "protocolMeaning": "EDISIO", "infoType": "15", "frequency": "868350"},"infos": {"subType": "25", "subTypeMeaning": "SET_TEMPERATURE", "id": "3021627888", "qualifier": "2", "info": "8968", "infoMeaning": "ETS-100, 3.5V", "add0": "2212", "add1": "0"}}}

_Décodage sur mon Rfplayer_ 
DEBUG (MainThread) [custom_components.rfplayer.rflib.rfpprotocol] handle packet: {'node': 'gateway', 'frameType': '0', 'cluster': '0', 'dataFlag': '1', 'rfLevel': '-58', 'floorNoise': '-98', 'rfQuality': '10', 'infoType': '15', 'frequency': '868350', 'protocol': 'EDISIO', 'subType': 'SET_TEMPERATURE', 'qualifier': '2', 'model': 'ETS-100', 'battery': ' 3.5', 'battery_unit': 'V', 'button': 25, 'command': 'SET_TEMPERATURE', 'temperature': 22.12, 'temperature_unit': '°C', 'hygrometry': 0.0, 'hygrometry_unit': '%', 'id': '3021627888', 'platform': 'sensor'}

L'hygrométrie n'existe pas sur mes types !

#### Autre sonde
DEBUG (MainThread) [custom_components.myrfplayer.rfplayerlib.protocol] received packet: ZIA33{ "frame" :{"header": {"frameType": "0", "cluster": "0", "dataFlag": "1", "rfLevel": "-60", "floorNoise": "-94", "rfQuality": "8", "protocol": "16", "protocolMeaning": "EDISIO", "infoType": "15", "frequency": "868350"},"infos": {"subType": "25", "subTypeMeaning": "SET_TEMPERATURE", "id": "1477804532", "qualifier": "2", "info": "8968", "infoMeaning": "ETS-100, 3.5V", "add0": "2087", "add1": "0"}}}
DEBUG (MainThread) [custom_components.myrfplayer.gateway] Received event: {"frame": {"header": {"frameType": "0", "cluster": "0", "dataFlag": "1", "rfLevel": "-60", "floorNoise": "-94", "rfQuality": "8", "protocol": "16", "protocolMeaning": "EDISIO", "infoType": "15", "frequency": "868350"}, "infos": {"subType": "25", "subTypeMeaning": "SET_TEMPERATURE", "id": "1477804532", "qualifier": "2", "info": "8968", "infoMeaning": "ETS-100, 3.5V", "add0": "2087", "add1": "0"}}}

**Comment by racletteparty** [comment]
It should possible to add à new profile in device_profiles.yam matching protocol edisio, infotype 15, subtype 25. Then we can extract add0 with json path and apply a 0.01 factor to get the temperature.

For hygrometry, either there is a way to know whether the device supports it or not, or you assume they all support hygrometer and sometime the value is always 0

**Comment by Doubledom45** [comment]
Test OK

**Comment by racletteparty** [comment]
Nice. If you want humidity. We need to make sure it's in add1 and what is the unit and conversion factor
